### ISSUE TITLE
node-druuid is incompatible with jest

### ISSUE THREAD

**Issue by wbk** [recurly/node-druuid#3]
A one-line test file:
```
require('druuid')
```

Fails with:
```
 FAIL  ./test.js
  ● Test suite failed to run

    TypeError: require is not a constructor
      
      at Object.<anonymous> (node_modules/bignum/index.js:4:14)
      at Object.<anonymous> (test.js:1:90)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.791s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This appears to be an issue internal to bignum's module loader which can be avoided by bumping node-druuid's dependency to it to 0.12 or higher with no adverse effects.

**Comment by drewish** [comment]
Yeah seems reasonable. You want to open up a PR?

**Comment by drewish** [comment]
1.4.0 is up. hopefully that works for you.
